blueprint:
  name: DK Shelly Dimmer
  description: Dimmar en lampa genom att använda en shelly i detached-mode.
  domain: automation
  input:
    target_light:
      name: Lampa
      description: Lampan som ska dimmas
      selector:
        entity:
          domain: light
    stopper_entity:
      name: Shelly - Input-sensor
      description: Input-sensorn för Shellyn. Används för att veta när dimmandet ska avbrytas
      selector:
        entity:
          domain: binary_sensor
    trigger_entity:
      name: Shelly - Longpush-sensor
      description: Longpush-sensorn för Shellyn. Används för att utföra dimmandet
      selector:
        entity:
          domain: binary_sensor
    max_brightness: 
      name: Max brightness
      description: Hur ljus lampan ska kunna bli som mest
      selector:
        number:
          min: 50
          max: 255
          step: 5
      default: 255
    min_brightness: 
      name: Min brightness
      description: Hur ljus lampan ska kunna bli som lägst
      selector:
        number:
          min: 0
          max: 50
          step: 5
      default: 30
    step:
      name: Antal steg från min till max ljusstyrka (eller tvärtom)
      description: Högre värde, långsammare dimmning
      selector:
        number:
          min: 5
          max: 50
      default: 10
    up_down_togglehelper:
      name: Helper
      description: Behövs för att hålla reda på vilket håll som lampan ska dimmas
      selector:
        entity:
          domain: input_boolean
variables:
  min_brightness: !input 'min_brightness'
  max_brightness: !input 'max_brightness'
  target_light: !input 'target_light'
  steps: !input 'step'
  step_smooth: '{{ (max_brightness-min_brightness)/steps }}'
  
trigger:
  - platform: state
    entity_id: !input trigger_entity
    to: 'on'

action:
  - repeat:
      until:
        - condition: state
          entity_id: !input stopper_entity
          state: 'off'
        # - condition: numeric_state
        #   entity_id: !input target_light
        #   attribute: brightness
        #   below: '{{ 0 + 2 }}'
      sequence:
        - choose:
            - conditions:
                - condition: state
                  entity_id: !input up_down_togglehelper
                  state: 'on'
                - condition: numeric_state
                  entity_id: !input target_light
                  attribute: brightness
                  below: !input max_brightness
              sequence:
                - service: light.turn_on
                  data:
                    brightness: '{{ [state_attr(target_light,"brightness") +step_smooth, max_brightness] | min }}'
                    transition: 0.25
                  target:
                    entity_id: !input target_light
            - conditions:
                - condition: state
                  entity_id: !input up_down_togglehelper
                  state: 'off'
                - condition: numeric_state
                  entity_id: !input target_light
                  attribute: brightness
                  above: !input min_brightness
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: !input target_light
                  data:
                    brightness: '{{ [state_attr(target_light,"brightness") -step_smooth, min_brightness] | max }}'
                    transition: 0.25
          default: []
        - delay:
            hours: 0
            minutes: 0
            seconds: 0
            milliseconds: 250
  - service: input_boolean.toggle
    target:
      entity_id: !input up_down_togglehelper
mode: restart
